name: kicad-exports@v2.3.2

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '.github/workflows/main.yml'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'
      - '.github/workflows/main.yml'
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: majnun1337/kicad-exports@v2.3.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: 'KiCAD_proj/devops-demo/devops-demo.sch'
      # optional - PCB design file
        board: 'KiCAD_proj/devops-demo/devops-demo.kicad_pcb'
      # optional - verbose output info
        verbose: 1
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
